//superuser search cities
GET https://kavatha-api.azurewebsites.net/search/cities?searchTerm=an
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
###

GET https://kavatha-api.azurewebsites.net/search/users?searchTerm=ja
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0

###
  
POST  https://kavatha-api.azurewebsites.net/auth/register
Content-Type: application/json

{
    "userId": 3,
    "username": "Nelly",
    "password": "pass",
    "role": "user"
}
###
POST  https://kavatha-api.azurewebsites.net/auth/register
Content-Type: application/json

{
    "userId": 2,
    "username": "simon",
    "password": "pass",
    "role": "superuser"
}
###

POST  https://kavatha-api.azurewebsites.net/auth/login
Content-Type: application/json

{
    "username": "daniel",
    "password": "pass"
}
###
POST https://kavatha-api.azurewebsites.net/comments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
Content-Type: application/json

{
  "orderId": 1,
  "userId": 1,
  "commentText": "The delivery was quick and the food was delicious!",
  "isComplaint": false,
  "isPraise": true
}

###
###

GET https://kavatha-api.azurewebsites.net/search/categories?searchTerm=salad
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0

###

GET https://kavatha-api.azurewebsites.net/users/order/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
###

GET https://kavatha-api.azurewebsites.net/orders/user/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
###

GET https://kavatha-api.azurewebsites.net/states/1/cities
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0

###

GET https://kavatha-api.azurewebsites.net/states/4/cities/3/restaurants
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0

###
// Service to fetch menu items by restaurant ID

GET https://kavatha-api.azurewebsites.net/restaurants/3/menu_items
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0


###
// Service to fetch menu items by category ID
GET https://kavatha-api.azurewebsites.net/categories/1/menu_items
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0


###
// Service to fetch the owner of a restaurant by restaurant ID
GET https://kavatha-api.azurewebsites.net/restaurants/3/owner
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0

###
// fetch all restaurants owned by a particular user
GET https://kavatha-api.azurewebsites.net/restaurantOwner/1/restaurants
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0


###
GET https://kavatha-api.azurewebsites.net/menuItem/categories/:id/menu_items

###

GET https://kavatha-api.azurewebsites.net/categories
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0

###

GET https://kavatha-api.azurewebsites.net/search/users?searchTerm=ja

###

POST https://kavatha-api.azurewebsites.net/restaurants
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
Content-Type: application/json

{
  "name": "The Zod Res",
  "streetAddress": "123 Main St",
  "zipCode": "12345",
  "cityId": 1
}
###

POST https://kavatha-api.azurewebsites.net/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
Content-Type: application/json

{
  "restaurantId": 5,
  "estimatedDeliveryTime": "2024-06-09T19:30:00Z",
  "deliveryAddressId": 1,
  "userId": 2,
  "price": 50.00,
  "discount": 5.00,
  "finalPrice": 45.00,
  "comment": "Please leave the order at the front door if no one answers."
}
###
###

POST https://kavatha-api.azurewebsites.net/address
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
Content-Type: application/json

{
  "streetAddress1": "123 Main St",
  "streetAddress2": "Apt 4B",
  "zipCode": "12345",
  "deliveryInstructions": "Leave at front door",
  "userId": 2,
  "cityId": 3
}
###

POST https://kavatha-api.azurewebsites.net/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
Content-Type: application/json

{
  "restaurantId": 5,
  "estimatedDeliveryTime": "2024-06-09T19:30:00Z",
  "deliveryAddressId": 1,
  "userId": 2,
  "price": 50.00,
  "discount": 5.00,
  "finalPrice": 45.00,
  "comment": "Please leave the order at the front door if no one answers."
}

###
POST http://localhost:8000/comments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
Content-Type: application/json

{
  "orderId": "2",
  "userId": 1,
  "commentText": "The delivery was quick and the food was delicious!",
  "isComplaint": false,
  "isPraise": true
}

###
POST http://localhost:8000/drivers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
Content-Type: application/json

{
  "id": 1,
  "carMake": "Nissan",
  "carModel": "Altima",
  "carYear": 2019,
  "userId": 3,
  "online": false,
  "delivering": true,
  "createdAt": "2024-06-12T12:00:00Z",
  "updatedAt": "2024-06-12T12:00:00Z"
}
###
DELETE http://localhost:8000/drivers/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0

###
PUT http://localhost:8000/states/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
Content-Type: application/json

{
    "name": "Tanzania",
    "code":"TZ"
}

###

PUT http://localhost:8000/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
Content-Type: application/json

{
    "name": "Kavatha"
}


###

PUT http://localhost:8000/restaurants/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
Content-Type: application/json

{
    "name": "Kavatha restaurant"
}

###

PUT http://localhost:8000/menuItem/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0
Content-Type: application/json

{
    "name": "rice",
    "active": true
}
###
GET http://localhost:8000/order/1/driver
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0

###
GET http://localhost:8000/orders/discounted/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0


###
DELETE http://localhost:8000/restaurants/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0

###

GET http://localhost:8000/statusCatalog
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYW5pZWwiLCJyb2xlIjoic3VwZXJ1c2VyIiwiZXhwIjoxNzE4Mjg5NDIxfQ.-ZxapEPjww2pSQcFnYHxOdrycW_B-D2tVnndNI2whS0

###
// Service to fetch the status of a particular order by order ID
GET http://localhost:8000/orderStatus/3/status
###

GET http://localhost:8000/states/4/cities/3/restaurants

###
// Service to fetch menu items by restaurant ID

GET http://localhost:8000/restaurants/3/menu_items

###
// Service to fetch menu items by category ID
GET http://localhost:8000/categories/6/menu_items

###
// Service to fetch the owner of a restaurant by restaurant ID
GET http://localhost:8000/api/restaurants/21/owner

###
// fetch all restaurants owned by a particular user
GET http://localhost:8000/restaurantOwner/1/restaurants
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJOZWxseSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MzIwNDAxfQ.fvGicJv01S30Hxs0WrYHJM5SdlS2iSoI1dzSxtakBcA

###
GET http://localhost:8000/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJOZWxseSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MzIwNDAxfQ.fvGicJv01S30Hxs0WrYHJM5SdlS2iSoI1dzSxtakBcA

###
POST  http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "jack",
    "password": "pass"
}

###
  
POST  http://localhost:8000/auth/register
Content-Type: application/json

{
    "userId": 3,
    "username": "Nelly",
    "password": "pass",
    "role": "user"
}



